/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package Dia5;

import java.util.Scanner;

public class App {
   
    public static void main(String[] args) {
        Scanner leitor = new Scanner(System.in);
        
        System.out.println("Digite seu nome: ");
        String nome = leitor.nextLine();
        
        System.out.println("Nota da primeira prova: ");
        float Nota1 = leitor.nextFloat();
        
        System.out.println("Nota da segunda prova: ");
        float Nota2 = leitor.nextFloat();
        
        System.out.println("Nota da terceira prova: ");
        float Nota3 = leitor.nextFloat();
        
        float media = (Nota1 + Nota2 + Nota3)/3;
        
        System.out.println("A média de " + nome + " é de " + media);
    }
}
